name: CI/CD

on: push

jobs:
  Dockerfile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: rendrick27/snakemake:latest

  Snakemake:
    needs: dockerfile
    runs-on: ubuntu-latest
    container:
      image: rendrick27/snakemake:latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Snakemake
      run: snakemake --use-conda all --cores all

  PEP8:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
    - uses: actions/checkout@v2
    - name: Install flake8
      run: pip install flake8
    - name: Run flake8
      run: flake8 TreeGenerator.py
